# Generated by Django 5.0.2 on 2024-03-01 06:41

import django.db.models.deletion
import django.utils.timezone
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=15, verbose_name='Имя')),
                ('m_name', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('l_name', models.CharField(max_length=15, verbose_name='Отчество')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
                ('date_employment', models.DateField(default=django.utils.timezone.now, verbose_name='Дата приема на работу')),
                ('salary', models.DecimalField(decimal_places=0, max_digits=6, verbose_name='Размер заработной платы')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='employer.employer', verbose_name='Начальник')),
            ],
            options={
                'verbose_name': 'Начальник',
                'verbose_name_plural': 'Начальники',
            },
        ),
    ]
